[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[phases.setup]
nixPkgs = [
  "nodejs_18",
  "npm",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "ttf-dejavu",
  "curl"
]

[phases.build]
cmds = [
  "npm ci --omit=dev",
  "npm run build"
]

[phases.start]
cmd = "node dist/index.js"

[start]
runImage = "nixos/nix:latest"
